// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see CellLineGroup
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CellLineGroupImpl
    extends CellLineGroup
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5512814982132579749L;

// HibernateEntityImpl.vsl merge-point
}