// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see VehicleType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class VehicleTypeImpl
    extends VehicleType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4981912625824857118L;

// HibernateEntityImpl.vsl merge-point
}