// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.structureservlet.androdomain;

/**
 * @see Structure
 */
// HibernateEntityImpl.vsl annotations merge-point
public class StructureImpl
    extends Structure
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5476086814005296027L;

// HibernateEntityImpl.vsl merge-point
}