// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see AffyData
 */
// HibernateEntityImpl.vsl annotations merge-point
public class AffyDataImpl
    extends AffyData
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6739183152408171234L;

// HibernateEntityImpl.vsl merge-point
}