// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see AffyIdentifierType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class AffyIdentifierTypeImpl
    extends AffyIdentifierType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 2027883822995183328L;

// HibernateEntityImpl.vsl merge-point
}