// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CellLineType
    implements Serializable, Comparable<CellLineType>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6853676991307254741L;

    // Generate 12 attributes
    private String pptpIdentifier;

    /**
     * 
     * @return this.pptpIdentifier String
     */
    public String getPptpIdentifier()
    {
        return this.pptpIdentifier;
    }

    /**
     * 
     * @param pptpIdentifierIn String
     */
    public void setPptpIdentifier(String pptpIdentifierIn)
    {
        this.pptpIdentifier = pptpIdentifierIn;
    }

    private String name;

    /**
     * 
     * @return this.name String
     */
    public String getName()
    {
        return this.name;
    }

    /**
     * 
     * @param nameIn String
     */
    public void setName(String nameIn)
    {
        this.name = nameIn;
    }

    private Boolean secondary;

    /**
     * 
     * @return this.secondary Boolean
     */
    public Boolean getSecondary()
    {
        return this.secondary;
    }

    /**
     * 
     * @param secondaryIn Boolean
     */
    public void setSecondary(Boolean secondaryIn)
    {
        this.secondary = secondaryIn;
    }

    private String source;

    /**
     * 
     * @return this.source String
     */
    public String getSource()
    {
        return this.source;
    }

    /**
     * 
     * @param sourceIn String
     */
    public void setSource(String sourceIn)
    {
        this.source = sourceIn;
    }

    private String dapIdentifier;

    /**
     * 
     * @return this.dapIdentifier String
     */
    public String getDapIdentifier()
    {
        return this.dapIdentifier;
    }

    /**
     * 
     * @param dapIdentifierIn String
     */
    public void setDapIdentifier(String dapIdentifierIn)
    {
        this.dapIdentifier = dapIdentifierIn;
    }

    private Integer sortOrder;

    /**
     * 
     * @return this.sortOrder Integer
     */
    public Integer getSortOrder()
    {
        return this.sortOrder;
    }

    /**
     * 
     * @param sortOrderIn Integer
     */
    public void setSortOrder(Integer sortOrderIn)
    {
        this.sortOrder = sortOrderIn;
    }

    private String masterbankidentifier;

    /**
     * 
     * @return this.masterbankidentifier String
     */
    public String getMasterbankidentifier()
    {
        return this.masterbankidentifier;
    }

    /**
     * 
     * @param masterbankidentifierIn String
     */
    public void setMasterbankidentifier(String masterbankidentifierIn)
    {
        this.masterbankidentifier = masterbankidentifierIn;
    }

    private String masterbankcellname;

    /**
     * 
     * @return this.masterbankcellname String
     */
    public String getMasterbankcellname()
    {
        return this.masterbankcellname;
    }

    /**
     * 
     * @param masterbankcellnameIn String
     */
    public void setMasterbankcellname(String masterbankcellnameIn)
    {
        this.masterbankcellname = masterbankcellnameIn;
    }

    private String masterbankprimary;

    /**
     * 
     * @return this.masterbankprimary String
     */
    public String getMasterbankprimary()
    {
        return this.masterbankprimary;
    }

    /**
     * 
     * @param masterbankprimaryIn String
     */
    public void setMasterbankprimary(String masterbankprimaryIn)
    {
        this.masterbankprimary = masterbankprimaryIn;
    }

    private String masterbankcelltype;

    /**
     * 
     * @return this.masterbankcelltype String
     */
    public String getMasterbankcelltype()
    {
        return this.masterbankcelltype;
    }

    /**
     * 
     * @param masterbankcelltypeIn String
     */
    public void setMasterbankcelltype(String masterbankcelltypeIn)
    {
        this.masterbankcelltype = masterbankcelltypeIn;
    }

    private String masterbankpanel;

    /**
     * 
     * @return this.masterbankpanel String
     */
    public String getMasterbankpanel()
    {
        return this.masterbankpanel;
    }

    /**
     * 
     * @param masterbankpanelIn String
     */
    public void setMasterbankpanel(String masterbankpanelIn)
    {
        this.masterbankpanel = masterbankpanelIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 4 associations
    private Collection<CellLineGroup> cellLineGroups = new HashSet<CellLineGroup>();

    /**
     * 
     * @return this.cellLineGroups Collection<CellLineGroup>
     */
    public Collection<CellLineGroup> getCellLineGroups()
    {
        return this.cellLineGroups;
    }

    /**
     * 
     * @param cellLineGroupsIn Collection<CellLineGroup>
     */
    public void setCellLineGroups(Collection<CellLineGroup> cellLineGroupsIn)
    {
        this.cellLineGroups = cellLineGroupsIn;
    }

    /**
     * 
     * @param elementToAdd CellLineGroup
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addCellLineGroups(CellLineGroup elementToAdd)
    {
        return this.cellLineGroups.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove CellLineGroup
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeCellLineGroups(CellLineGroup elementToRemove)
    {
        return this.cellLineGroups.remove(elementToRemove);
    }

    private PanelType panelType;

    /**
     * 
     * @return this.panelType PanelType
     */
    public PanelType getPanelType()
    {
        return this.panelType;
    }

    /**
     * 
     * @param panelTypeIn PanelType
     */
    public void setPanelType(PanelType panelTypeIn)
    {
        this.panelType = panelTypeIn;
    }

    private CellType cellType;

    /**
     * 
     * @return this.cellType CellType
     */
    public CellType getCellType()
    {
        return this.cellType;
    }

    /**
     * 
     * @param cellTypeIn CellType
     */
    public void setCellType(CellType cellTypeIn)
    {
        this.cellType = cellTypeIn;
    }

    private Collection<AffyData> affyDatas = new HashSet<AffyData>();

    /**
     * 
     * @return this.affyDatas Collection<AffyData>
     */
    public Collection<AffyData> getAffyDatas()
    {
        return this.affyDatas;
    }

    /**
     * 
     * @param affyDatasIn Collection<AffyData>
     */
    public void setAffyDatas(Collection<AffyData> affyDatasIn)
    {
        this.affyDatas = affyDatasIn;
    }

    /**
     * 
     * @param elementToAdd AffyData
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addAffyDatas(AffyData elementToAdd)
    {
        return this.affyDatas.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove AffyData
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeAffyDatas(AffyData elementToRemove)
    {
        return this.affyDatas.remove(elementToRemove);
    }

    /**
     * Returns <code>true</code> if the argument is an CellLineType instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CellLineType))
        {
            return false;
        }
        final CellLineType that = (CellLineType)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CellLineType}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CellLineType}.
         * @return new CellLineTypeImpl()
         */
        public static CellLineType newInstance()
        {
            return new CellLineTypeImpl();
        }

        /**
         * Constructs a new instance of {@link CellLineType}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param pptpIdentifier String
         * @param name String
         * @param source String
         * @param dapIdentifier String
         * @param masterbankidentifier String
         * @param masterbankcellname String
         * @param masterbankcelltype String
         * @param masterbankpanel String
         * @param panelType PanelType
         * @param cellType CellType
         * @return newInstance
         */
        public static CellLineType newInstance(String pptpIdentifier, String name, String source, String dapIdentifier, String masterbankidentifier, String masterbankcellname, String masterbankcelltype, String masterbankpanel, PanelType panelType, CellType cellType)
        {
            final CellLineType entity = new CellLineTypeImpl();
            entity.setPptpIdentifier(pptpIdentifier);
            entity.setName(name);
            entity.setSource(source);
            entity.setDapIdentifier(dapIdentifier);
            entity.setMasterbankidentifier(masterbankidentifier);
            entity.setMasterbankcellname(masterbankcellname);
            entity.setMasterbankcelltype(masterbankcelltype);
            entity.setMasterbankpanel(masterbankpanel);
            entity.setPanelType(panelType);
            entity.setCellType(cellType);
            return entity;
        }

        /**
         * Constructs a new instance of {@link CellLineType}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param pptpIdentifier String
         * @param name String
         * @param secondary Boolean
         * @param source String
         * @param dapIdentifier String
         * @param sortOrder Integer
         * @param masterbankidentifier String
         * @param masterbankcellname String
         * @param masterbankprimary String
         * @param masterbankcelltype String
         * @param masterbankpanel String
         * @param cellLineGroups Collection<CellLineGroup>
         * @param panelType PanelType
         * @param cellType CellType
         * @param affyDatas Collection<AffyData>
         * @return newInstance CellLineType
         */
        public static CellLineType newInstance(String pptpIdentifier, String name, Boolean secondary, String source, String dapIdentifier, Integer sortOrder, String masterbankidentifier, String masterbankcellname, String masterbankprimary, String masterbankcelltype, String masterbankpanel, Collection<CellLineGroup> cellLineGroups, PanelType panelType, CellType cellType, Collection<AffyData> affyDatas)
        {
            final CellLineType entity = new CellLineTypeImpl();
            entity.setPptpIdentifier(pptpIdentifier);
            entity.setName(name);
            entity.setSecondary(secondary);
            entity.setSource(source);
            entity.setDapIdentifier(dapIdentifier);
            entity.setSortOrder(sortOrder);
            entity.setMasterbankidentifier(masterbankidentifier);
            entity.setMasterbankcellname(masterbankcellname);
            entity.setMasterbankprimary(masterbankprimary);
            entity.setMasterbankcelltype(masterbankcelltype);
            entity.setMasterbankpanel(masterbankpanel);
            entity.setCellLineGroups(cellLineGroups);
            entity.setPanelType(panelType);
            entity.setCellType(cellType);
            entity.setAffyDatas(affyDatas);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CellLineType o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getPptpIdentifier() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getPptpIdentifier().compareTo(o.getPptpIdentifier()));
            }
            if (this.getName() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(o.getName()));
            }
            if (this.getSecondary() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSecondary().compareTo(o.getSecondary()));
            }
            if (this.getSource() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSource().compareTo(o.getSource()));
            }
            if (this.getDapIdentifier() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getDapIdentifier().compareTo(o.getDapIdentifier()));
            }
            if (this.getSortOrder() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSortOrder().compareTo(o.getSortOrder()));
            }
            if (this.getMasterbankidentifier() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMasterbankidentifier().compareTo(o.getMasterbankidentifier()));
            }
            if (this.getMasterbankcellname() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMasterbankcellname().compareTo(o.getMasterbankcellname()));
            }
            if (this.getMasterbankprimary() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMasterbankprimary().compareTo(o.getMasterbankprimary()));
            }
            if (this.getMasterbankcelltype() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMasterbankcelltype().compareTo(o.getMasterbankcelltype()));
            }
            if (this.getMasterbankpanel() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMasterbankpanel().compareTo(o.getMasterbankpanel()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}