// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see CellLineMaster
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CellLineMasterImpl
    extends CellLineMaster
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 2525062597709239446L;

// HibernateEntityImpl.vsl merge-point
}