// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see CompoundMaster
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CompoundMasterImpl
    extends CompoundMaster
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -93079890162922993L;

// HibernateEntityImpl.vsl merge-point
}