// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class GroupRoleType
    implements Serializable, Comparable<GroupRoleType>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5642287508689901930L;

    // Generate 2 attributes
    private String displayName;

    /**
     * 
     * @return this.displayName String
     */
    public String getDisplayName()
    {
        return this.displayName;
    }

    /**
     * 
     * @param displayNameIn String
     */
    public void setDisplayName(String displayNameIn)
    {
        this.displayName = displayNameIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 2 associations
    private Collection<Summary> summaries = new HashSet<Summary>();

    /**
     * 
     * @return this.summaries Collection<Summary>
     */
    public Collection<Summary> getSummaries()
    {
        return this.summaries;
    }

    /**
     * 
     * @param summariesIn Collection<Summary>
     */
    public void setSummaries(Collection<Summary> summariesIn)
    {
        this.summaries = summariesIn;
    }

    /**
     * 
     * @param elementToAdd Summary
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addSummaries(Summary elementToAdd)
    {
        return this.summaries.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove Summary
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeSummaries(Summary elementToRemove)
    {
        return this.summaries.remove(elementToRemove);
    }

    private Collection<MouseGroup> mouseGroups = new HashSet<MouseGroup>();

    /**
     * 
     * @return this.mouseGroups Collection<MouseGroup>
     */
    public Collection<MouseGroup> getMouseGroups()
    {
        return this.mouseGroups;
    }

    /**
     * 
     * @param mouseGroupsIn Collection<MouseGroup>
     */
    public void setMouseGroups(Collection<MouseGroup> mouseGroupsIn)
    {
        this.mouseGroups = mouseGroupsIn;
    }

    /**
     * 
     * @param elementToAdd MouseGroup
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addMouseGroups(MouseGroup elementToAdd)
    {
        return this.mouseGroups.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove MouseGroup
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeMouseGroups(MouseGroup elementToRemove)
    {
        return this.mouseGroups.remove(elementToRemove);
    }

    /**
     * Returns <code>true</code> if the argument is an GroupRoleType instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof GroupRoleType))
        {
            return false;
        }
        final GroupRoleType that = (GroupRoleType)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link GroupRoleType}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link GroupRoleType}.
         * @return new GroupRoleTypeImpl()
         */
        public static GroupRoleType newInstance()
        {
            return new GroupRoleTypeImpl();
        }

        /**
         * Constructs a new instance of {@link GroupRoleType}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param displayName String
         * @return newInstance
         */
        public static GroupRoleType newInstance(String displayName)
        {
            final GroupRoleType entity = new GroupRoleTypeImpl();
            entity.setDisplayName(displayName);
            return entity;
        }

        /**
         * Constructs a new instance of {@link GroupRoleType}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param displayName String
         * @param summaries Collection<Summary>
         * @param mouseGroups Collection<MouseGroup>
         * @return newInstance GroupRoleType
         */
        public static GroupRoleType newInstance(String displayName, Collection<Summary> summaries, Collection<MouseGroup> mouseGroups)
        {
            final GroupRoleType entity = new GroupRoleTypeImpl();
            entity.setDisplayName(displayName);
            entity.setSummaries(summaries);
            entity.setMouseGroups(mouseGroups);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(GroupRoleType o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getDisplayName() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getDisplayName().compareTo(o.getDisplayName()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}