// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see Mouse
 */
// HibernateEntityImpl.vsl annotations merge-point
public class MouseImpl
    extends Mouse
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4317257208370680718L;

// HibernateEntityImpl.vsl merge-point
}