// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see MouseType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class MouseTypeImpl
    extends MouseType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7369607654406947142L;

// HibernateEntityImpl.vsl merge-point
}