// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see MtdStudy
 */
// HibernateEntityImpl.vsl annotations merge-point
public class MtdStudyImpl
    extends MtdStudy
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3727959635290529695L;

// HibernateEntityImpl.vsl merge-point
}