// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see ScheduleType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class ScheduleTypeImpl
    extends ScheduleType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3292418196639125125L;

// HibernateEntityImpl.vsl merge-point
}