// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class Cmpd
    implements Serializable, Comparable<Cmpd>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3246601760844230205L;

    // Generate 1 attributes
    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    private Collection<CmpdListMember> cmpdListMembers = new HashSet<CmpdListMember>();

    /**
     * 
     * @return this.cmpdListMembers Collection<CmpdListMember>
     */
    public Collection<CmpdListMember> getCmpdListMembers()
    {
        return this.cmpdListMembers;
    }

    /**
     * 
     * @param cmpdListMembersIn Collection<CmpdListMember>
     */
    public void setCmpdListMembers(Collection<CmpdListMember> cmpdListMembersIn)
    {
        this.cmpdListMembers = cmpdListMembersIn;
    }

    /**
     * 
     * @param elementToAdd CmpdListMember
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addCmpdListMembers(CmpdListMember elementToAdd)
    {
        return this.cmpdListMembers.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove CmpdListMember
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeCmpdListMembers(CmpdListMember elementToRemove)
    {
        return this.cmpdListMembers.remove(elementToRemove);
    }

    /**
     * Returns <code>true</code> if the argument is an Cmpd instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Cmpd))
        {
            return false;
        }
        final Cmpd that = (Cmpd)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link Cmpd}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link Cmpd}.
         * @return new CmpdImpl()
         */
        public static Cmpd newInstance()
        {
            return new CmpdImpl();
        }


        /**
         * Constructs a new instance of {@link Cmpd}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param cmpdListMembers Collection<CmpdListMember>
         * @return newInstance Cmpd
         */
        public static Cmpd newInstance(Collection<CmpdListMember> cmpdListMembers)
        {
            final Cmpd entity = new CmpdImpl();
            entity.setCmpdListMembers(cmpdListMembers);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(Cmpd o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}