// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdRelationType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdRelationTypeImpl
    extends CmpdRelationType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3597232500898381797L;

// HibernateEntityImpl.vsl merge-point
}