// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdKnownSalt
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdKnownSaltImpl
    extends CmpdKnownSalt
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1278680713486986339L;

// HibernateEntityImpl.vsl merge-point
}