// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdList
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdListImpl
    extends CmpdList
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4411415242228169065L;

// HibernateEntityImpl.vsl merge-point
}