// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdTarget
    implements Serializable, Comparable<CmpdTarget>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8881189308257702707L;

    // Generate 2 attributes
    private String target;

    /**
     * 
     * @return this.target String
     */
    public String getTarget()
    {
        return this.target;
    }

    /**
     * 
     * @param targetIn String
     */
    public void setTarget(String targetIn)
    {
        this.target = targetIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    /**
     * Returns <code>true</code> if the argument is an CmpdTarget instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdTarget))
        {
            return false;
        }
        final CmpdTarget that = (CmpdTarget)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdTarget}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdTarget}.
         * @return new CmpdTargetImpl()
         */
        public static CmpdTarget newInstance()
        {
            return new CmpdTargetImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdTarget}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param target String
         * @return newInstance CmpdTarget
         */
        public static CmpdTarget newInstance(String target)
        {
            final CmpdTarget entity = new CmpdTargetImpl();
            entity.setTarget(target);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdTarget o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getTarget() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getTarget().compareTo(o.getTarget()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}