// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdBioAssay
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdBioAssayImpl
    extends CmpdBioAssay
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -368057500139744467L;

// HibernateEntityImpl.vsl merge-point
}