// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdInventory
    implements Serializable, Comparable<CmpdInventory>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4722766313337932915L;

    // Generate 2 attributes
    private Double inventory;

    /**
     * 
     * @return this.inventory Double
     */
    public Double getInventory()
    {
        return this.inventory;
    }

    /**
     * 
     * @param inventoryIn Double
     */
    public void setInventory(Double inventoryIn)
    {
        this.inventory = inventoryIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    /**
     * Returns <code>true</code> if the argument is an CmpdInventory instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdInventory))
        {
            return false;
        }
        final CmpdInventory that = (CmpdInventory)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdInventory}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdInventory}.
         * @return new CmpdInventoryImpl()
         */
        public static CmpdInventory newInstance()
        {
            return new CmpdInventoryImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdInventory}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param inventory Double
         * @return newInstance CmpdInventory
         */
        public static CmpdInventory newInstance(Double inventory)
        {
            final CmpdInventory entity = new CmpdInventoryImpl();
            entity.setInventory(inventory);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdInventory o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getInventory() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getInventory().compareTo(o.getInventory()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}