// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdListMember
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdListMemberImpl
    extends CmpdListMember
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2161843131792164045L;

// HibernateEntityImpl.vsl merge-point
}