// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdAliasType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdAliasTypeImpl
    extends CmpdAliasType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5746628861885042647L;

// HibernateEntityImpl.vsl merge-point
}