// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see CmpdSet
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdSetImpl
    extends CmpdSet
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5236261034937113446L;

// HibernateEntityImpl.vsl merge-point
}