// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

/**
 * @see Cmpd
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdImpl
    extends Cmpd
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3246601760844230205L;

// HibernateEntityImpl.vsl merge-point
}