// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.domain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdAliasType
    implements Serializable, Comparable<CmpdAliasType>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5746628861885042647L;

    // Generate 2 attributes
    private String aliasType;

    /**
     * 
     * @return this.aliasType String
     */
    public String getAliasType()
    {
        return this.aliasType;
    }

    /**
     * 
     * @param aliasTypeIn String
     */
    public void setAliasType(String aliasTypeIn)
    {
        this.aliasType = aliasTypeIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    /**
     * Returns <code>true</code> if the argument is an CmpdAliasType instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdAliasType))
        {
            return false;
        }
        final CmpdAliasType that = (CmpdAliasType)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdAliasType}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdAliasType}.
         * @return new CmpdAliasTypeImpl()
         */
        public static CmpdAliasType newInstance()
        {
            return new CmpdAliasTypeImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdAliasType}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param aliasType String
         * @return newInstance CmpdAliasType
         */
        public static CmpdAliasType newInstance(String aliasType)
        {
            final CmpdAliasType entity = new CmpdAliasTypeImpl();
            entity.setAliasType(aliasType);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdAliasType o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getAliasType() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getAliasType().compareTo(o.getAliasType()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}