// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see AdHocCmpdFragmentStructure
 */
// HibernateEntityImpl.vsl annotations merge-point
public class AdHocCmpdFragmentStructureImpl
    extends AdHocCmpdFragmentStructure
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5978259496014727751L;

// HibernateEntityImpl.vsl merge-point
}