// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdFragment
    implements Serializable, Comparable<CmpdFragment>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5292800595862336000L;

    // Generate 1 attributes
    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 5 associations
    private CmpdFragmentStructure cmpdFragmentStructure;

    /**
     * 
     * @return this.cmpdFragmentStructure CmpdFragmentStructure
     */
    public CmpdFragmentStructure getCmpdFragmentStructure()
    {
        return this.cmpdFragmentStructure;
    }

    /**
     * 
     * @param cmpdFragmentStructureIn CmpdFragmentStructure
     */
    public void setCmpdFragmentStructure(CmpdFragmentStructure cmpdFragmentStructureIn)
    {
        this.cmpdFragmentStructure = cmpdFragmentStructureIn;
    }

    private CmpdKnownSalt cmpdKnownSalt;

    /**
     * 
     * @return this.cmpdKnownSalt CmpdKnownSalt
     */
    public CmpdKnownSalt getCmpdKnownSalt()
    {
        return this.cmpdKnownSalt;
    }

    /**
     * 
     * @param cmpdKnownSaltIn CmpdKnownSalt
     */
    public void setCmpdKnownSalt(CmpdKnownSalt cmpdKnownSaltIn)
    {
        this.cmpdKnownSalt = cmpdKnownSaltIn;
    }

    private CmpdFragmentPChem cmpdFragmentPChem;

    /**
     * 
     * @return this.cmpdFragmentPChem CmpdFragmentPChem
     */
    public CmpdFragmentPChem getCmpdFragmentPChem()
    {
        return this.cmpdFragmentPChem;
    }

    /**
     * 
     * @param cmpdFragmentPChemIn CmpdFragmentPChem
     */
    public void setCmpdFragmentPChem(CmpdFragmentPChem cmpdFragmentPChemIn)
    {
        this.cmpdFragmentPChem = cmpdFragmentPChemIn;
    }

    /**
     * Returns <code>true</code> if the argument is an CmpdFragment instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdFragment))
        {
            return false;
        }
        final CmpdFragment that = (CmpdFragment)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdFragment}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdFragment}.
         * @return new CmpdFragmentImpl()
         */
        public static CmpdFragment newInstance()
        {
            return new CmpdFragmentImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdFragment}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param cmpdFragmentStructure CmpdFragmentStructure
         * @param cmpdKnownSalt CmpdKnownSalt
         * @param cmpdFragmentPChem CmpdFragmentPChem
         * @return newInstance CmpdFragment
         */
        public static CmpdFragment newInstance(CmpdFragmentStructure cmpdFragmentStructure, CmpdKnownSalt cmpdKnownSalt, CmpdFragmentPChem cmpdFragmentPChem)
        {
            final CmpdFragment entity = new CmpdFragmentImpl();
            entity.setCmpdFragmentStructure(cmpdFragmentStructure);
            entity.setCmpdKnownSalt(cmpdKnownSalt);
            entity.setCmpdFragmentPChem(cmpdFragmentPChem);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdFragment o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}