// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdFragmentStructure
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdFragmentStructureImpl
    extends CmpdFragmentStructure
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7866210453678709014L;

// HibernateEntityImpl.vsl merge-point
}