// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdAlias
    implements Serializable, Comparable<CmpdAlias>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7478702764050567991L;

    // Generate 2 attributes
    private String alias;

    /**
     * 
     * @return this.alias String
     */
    public String getAlias()
    {
        return this.alias;
    }

    /**
     * 
     * @param aliasIn String
     */
    public void setAlias(String aliasIn)
    {
        this.alias = aliasIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 2 associations
    private CmpdAliasType cmpdAliasType;

    /**
     * 
     * @return this.cmpdAliasType CmpdAliasType
     */
    public CmpdAliasType getCmpdAliasType()
    {
        return this.cmpdAliasType;
    }

    /**
     * 
     * @param cmpdAliasTypeIn CmpdAliasType
     */
    public void setCmpdAliasType(CmpdAliasType cmpdAliasTypeIn)
    {
        this.cmpdAliasType = cmpdAliasTypeIn;
    }

    /**
     * Returns <code>true</code> if the argument is an CmpdAlias instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdAlias))
        {
            return false;
        }
        final CmpdAlias that = (CmpdAlias)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdAlias}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdAlias}.
         * @return new CmpdAliasImpl()
         */
        public static CmpdAlias newInstance()
        {
            return new CmpdAliasImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdAlias}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param alias String
         * @param cmpdAliasType CmpdAliasType
         * @return newInstance CmpdAlias
         */
        public static CmpdAlias newInstance(String alias, CmpdAliasType cmpdAliasType)
        {
            final CmpdAlias entity = new CmpdAliasImpl();
            entity.setAlias(alias);
            entity.setCmpdAliasType(cmpdAliasType);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdAlias o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getAlias() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getAlias().compareTo(o.getAlias()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}