// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdPubChemSid
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdPubChemSidImpl
    extends CmpdPubChemSid
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -546413857089862758L;

// HibernateEntityImpl.vsl merge-point
}