// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdPubChemSid
    implements Serializable, Comparable<CmpdPubChemSid>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -546413857089862758L;

    // Generate 2 attributes
    private Long sid;

    /**
     * 
     * @return this.sid Long
     */
    public Long getSid()
    {
        return this.sid;
    }

    /**
     * 
     * @param sidIn Long
     */
    public void setSid(Long sidIn)
    {
        this.sid = sidIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    /**
     * Returns <code>true</code> if the argument is an CmpdPubChemSid instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdPubChemSid))
        {
            return false;
        }
        final CmpdPubChemSid that = (CmpdPubChemSid)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdPubChemSid}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdPubChemSid}.
         * @return new CmpdPubChemSidImpl()
         */
        public static CmpdPubChemSid newInstance()
        {
            return new CmpdPubChemSidImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdPubChemSid}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param sid Long
         * @return newInstance CmpdPubChemSid
         */
        public static CmpdPubChemSid newInstance(Long sid)
        {
            final CmpdPubChemSid entity = new CmpdPubChemSidImpl();
            entity.setSid(sid);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdPubChemSid o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getSid() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSid().compareTo(o.getSid()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}