// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdRelated
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdRelatedImpl
    extends CmpdRelated
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7994166388658971012L;

// HibernateEntityImpl.vsl merge-point
}