// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdFragment
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdFragmentImpl
    extends CmpdFragment
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5292800595862336000L;

// HibernateEntityImpl.vsl merge-point
}