// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdFragmentPChem
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdFragmentPChemImpl
    extends CmpdFragmentPChem
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5154595813878737953L;

// HibernateEntityImpl.vsl merge-point
}