// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see RdkitMol
 */
// HibernateEntityImpl.vsl annotations merge-point
public class RdkitMolImpl
    extends RdkitMol
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6028571639998291790L;

// HibernateEntityImpl.vsl merge-point
}