// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class RdkitMol
    implements Serializable, Comparable<RdkitMol>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6028571639998291790L;

    // Generate 3 attributes
    private Integer nsc;

    /**
     * 
     * @return this.nsc Integer
     */
    public Integer getNsc()
    {
        return this.nsc;
    }

    /**
     * 
     * @param nscIn Integer
     */
    public void setNsc(Integer nscIn)
    {
        this.nsc = nscIn;
    }

    private String mol;

    /**
     * 
     * @return this.mol String
     */
    public String getMol()
    {
        return this.mol;
    }

    /**
     * 
     * @param molIn String
     */
    public void setMol(String molIn)
    {
        this.mol = molIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    private StandardizedSmiles standardizedSmiles;

    /**
     * 
     * @return this.standardizedSmiles StandardizedSmiles
     */
    public StandardizedSmiles getStandardizedSmiles()
    {
        return this.standardizedSmiles;
    }

    /**
     * 
     * @param standardizedSmilesIn StandardizedSmiles
     */
    public void setStandardizedSmiles(StandardizedSmiles standardizedSmilesIn)
    {
        this.standardizedSmiles = standardizedSmilesIn;
    }

    /**
     * Returns <code>true</code> if the argument is an RdkitMol instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof RdkitMol))
        {
            return false;
        }
        final RdkitMol that = (RdkitMol)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link RdkitMol}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link RdkitMol}.
         * @return new RdkitMolImpl()
         */
        public static RdkitMol newInstance()
        {
            return new RdkitMolImpl();
        }

        /**
         * Constructs a new instance of {@link RdkitMol}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param mol String
         * @param standardizedSmiles StandardizedSmiles
         * @return newInstance
         */
        public static RdkitMol newInstance(String mol, StandardizedSmiles standardizedSmiles)
        {
            final RdkitMol entity = new RdkitMolImpl();
            entity.setMol(mol);
            entity.setStandardizedSmiles(standardizedSmiles);
            return entity;
        }

        /**
         * Constructs a new instance of {@link RdkitMol}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param nsc Integer
         * @param mol String
         * @param standardizedSmiles StandardizedSmiles
         * @return newInstance RdkitMol
         */
        public static RdkitMol newInstance(Integer nsc, String mol, StandardizedSmiles standardizedSmiles)
        {
            final RdkitMol entity = new RdkitMolImpl();
            entity.setNsc(nsc);
            entity.setMol(mol);
            entity.setStandardizedSmiles(standardizedSmiles);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(RdkitMol o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getNsc() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getNsc().compareTo(o.getNsc()));
            }
            if (this.getMol() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMol().compareTo(o.getMol()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}