// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdRelated
    implements Serializable, Comparable<CmpdRelated>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7994166388658971012L;

    // Generate 1 attributes
    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 3 associations
    private NscCmpd nscCmpd;

    /**
     * 
     * @return this.nscCmpd NscCmpd
     */
    public NscCmpd getNscCmpd()
    {
        return this.nscCmpd;
    }

    /**
     * 
     * @param nscCmpdIn NscCmpd
     */
    public void setNscCmpd(NscCmpd nscCmpdIn)
    {
        this.nscCmpd = nscCmpdIn;
    }

    private CmpdRelationType cmpdRelationType;

    /**
     * 
     * @return this.cmpdRelationType CmpdRelationType
     */
    public CmpdRelationType getCmpdRelationType()
    {
        return this.cmpdRelationType;
    }

    /**
     * 
     * @param cmpdRelationTypeIn CmpdRelationType
     */
    public void setCmpdRelationType(CmpdRelationType cmpdRelationTypeIn)
    {
        this.cmpdRelationType = cmpdRelationTypeIn;
    }

    /**
     * Returns <code>true</code> if the argument is an CmpdRelated instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdRelated))
        {
            return false;
        }
        final CmpdRelated that = (CmpdRelated)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdRelated}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdRelated}.
         * @return new CmpdRelatedImpl()
         */
        public static CmpdRelated newInstance()
        {
            return new CmpdRelatedImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdRelated}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param nscCmpd NscCmpd
         * @param cmpdRelationType CmpdRelationType
         * @return newInstance CmpdRelated
         */
        public static CmpdRelated newInstance(NscCmpd nscCmpd, CmpdRelationType cmpdRelationType)
        {
            final CmpdRelated entity = new CmpdRelatedImpl();
            entity.setNscCmpd(nscCmpd);
            entity.setCmpdRelationType(cmpdRelationType);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdRelated o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}