// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdView
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdViewImpl
    extends CmpdView
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4463222987001780916L;

// HibernateEntityImpl.vsl merge-point
}