// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdProject
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdProjectImpl
    extends CmpdProject
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4691884644037899978L;

// HibernateEntityImpl.vsl merge-point
}