// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdTarget
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdTargetImpl
    extends CmpdTarget
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8881189308257702707L;

// HibernateEntityImpl.vsl merge-point
}