// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see CellType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CellTypeImpl
    extends CellType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2741440599139157405L;

// HibernateEntityImpl.vsl merge-point
}