// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see CompoundType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CompoundTypeImpl
    extends CompoundType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7893499006669078660L;

// HibernateEntityImpl.vsl merge-point
}