// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class PanelType
    implements Serializable, Comparable<PanelType>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5956324993133824996L;

    // Generate 3 attributes
    private String displayName;

    /**
     * 
     * @return this.displayName String
     */
    public String getDisplayName()
    {
        return this.displayName;
    }

    /**
     * 
     * @param displayNameIn String
     */
    public void setDisplayName(String displayNameIn)
    {
        this.displayName = displayNameIn;
    }

    private Integer sortOrder;

    /**
     * 
     * @return this.sortOrder Integer
     */
    public Integer getSortOrder()
    {
        return this.sortOrder;
    }

    /**
     * 
     * @param sortOrderIn Integer
     */
    public void setSortOrder(Integer sortOrderIn)
    {
        this.sortOrder = sortOrderIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    private Collection<CellLineType> cellLineTypes = new HashSet<CellLineType>();

    /**
     * 
     * @return this.cellLineTypes Collection<CellLineType>
     */
    public Collection<CellLineType> getCellLineTypes()
    {
        return this.cellLineTypes;
    }

    /**
     * 
     * @param cellLineTypesIn Collection<CellLineType>
     */
    public void setCellLineTypes(Collection<CellLineType> cellLineTypesIn)
    {
        this.cellLineTypes = cellLineTypesIn;
    }

    /**
     * 
     * @param elementToAdd CellLineType
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addCellLineTypes(CellLineType elementToAdd)
    {
        return this.cellLineTypes.add(elementToAdd);
    }

    /**
     * 
     * @param elementToRemove CellLineType
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeCellLineTypes(CellLineType elementToRemove)
    {
        return this.cellLineTypes.remove(elementToRemove);
    }

    /**
     * Returns <code>true</code> if the argument is an PanelType instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof PanelType))
        {
            return false;
        }
        final PanelType that = (PanelType)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link PanelType}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link PanelType}.
         * @return new PanelTypeImpl()
         */
        public static PanelType newInstance()
        {
            return new PanelTypeImpl();
        }

        /**
         * Constructs a new instance of {@link PanelType}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param displayName String
         * @return newInstance
         */
        public static PanelType newInstance(String displayName)
        {
            final PanelType entity = new PanelTypeImpl();
            entity.setDisplayName(displayName);
            return entity;
        }

        /**
         * Constructs a new instance of {@link PanelType}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param displayName String
         * @param sortOrder Integer
         * @param cellLineTypes Collection<CellLineType>
         * @return newInstance PanelType
         */
        public static PanelType newInstance(String displayName, Integer sortOrder, Collection<CellLineType> cellLineTypes)
        {
            final PanelType entity = new PanelTypeImpl();
            entity.setDisplayName(displayName);
            entity.setSortOrder(sortOrder);
            entity.setCellLineTypes(cellLineTypes);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(PanelType o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getDisplayName() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getDisplayName().compareTo(o.getDisplayName()));
            }
            if (this.getSortOrder() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSortOrder().compareTo(o.getSortOrder()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}