// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see PanelType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class PanelTypeImpl
    extends PanelType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5956324993133824996L;

// HibernateEntityImpl.vsl merge-point
}