// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see RetestType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class RetestTypeImpl
    extends RetestType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5458324966537413925L;

// HibernateEntityImpl.vsl merge-point
}