// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.pptp.androdomain;

/**
 * @see TreatmentRouteType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class TreatmentRouteTypeImpl
    extends TreatmentRouteType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 238727498678150504L;

// HibernateEntityImpl.vsl merge-point
}