// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see AdHocCmpdFragmentPChem
 */
// HibernateEntityImpl.vsl annotations merge-point
public class AdHocCmpdFragmentPChemImpl
    extends AdHocCmpdFragmentPChem
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6017542782082896123L;

// HibernateEntityImpl.vsl merge-point
}