// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

import java.io.Serializable;

/**
 * 
 */
// HibernateEntity.vsl annotations merge-point
public abstract class CmpdRelationType
    implements Serializable, Comparable<CmpdRelationType>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3597232500898381797L;

    // Generate 2 attributes
    private String relationType;

    /**
     * 
     * @return this.relationType String
     */
    public String getRelationType()
    {
        return this.relationType;
    }

    /**
     * 
     * @param relationTypeIn String
     */
    public void setRelationType(String relationTypeIn)
    {
        this.relationType = relationTypeIn;
    }

    private Long id;

    /**
     * 
     * @return this.id Long
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * 
     * @param idIn Long
     */
    public void setId(Long idIn)
    {
        this.id = idIn;
    }

    // Generate 1 associations
    private CmpdRelated cmpdRelated;

    /**
     * 
     * @return this.cmpdRelated CmpdRelated
     */
    public CmpdRelated getCmpdRelated()
    {
        return this.cmpdRelated;
    }

    /**
     * 
     * @param cmpdRelatedIn CmpdRelated
     */
    public void setCmpdRelated(CmpdRelated cmpdRelatedIn)
    {
        this.cmpdRelated = cmpdRelatedIn;
    }

    /**
     * Returns <code>true</code> if the argument is an CmpdRelationType instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CmpdRelationType))
        {
            return false;
        }
        final CmpdRelationType that = (CmpdRelationType)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link CmpdRelationType}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link CmpdRelationType}.
         * @return new CmpdRelationTypeImpl()
         */
        public static CmpdRelationType newInstance()
        {
            return new CmpdRelationTypeImpl();
        }


        /**
         * Constructs a new instance of {@link CmpdRelationType}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param relationType String
         * @param cmpdRelated CmpdRelated
         * @return newInstance CmpdRelationType
         */
        public static CmpdRelationType newInstance(String relationType, CmpdRelated cmpdRelated)
        {
            final CmpdRelationType entity = new CmpdRelationTypeImpl();
            entity.setRelationType(relationType);
            entity.setCmpdRelated(cmpdRelated);
            return entity;
        }
    }

    /**
     * @see Comparable#compareTo
     */
    public int compareTo(CmpdRelationType o)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(o.getId());
        }
        else
        {
            if (this.getRelationType() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getRelationType().compareTo(o.getRelationType()));
            }
        }
        return cmp;
    }
// HibernateEntity.vsl merge-point
}