// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdInventory
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdInventoryImpl
    extends CmpdInventory
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4722766313337932915L;

// HibernateEntityImpl.vsl merge-point
}