// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package mwk.datasystem.androdomain;

/**
 * @see CmpdPlate
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CmpdPlateImpl
    extends CmpdPlate
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1152508331528659425L;

// HibernateEntityImpl.vsl merge-point
}