// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see AdHocDrugTracker
 */
// HibernateEntityImpl.vsl annotations merge-point
public class AdHocDrugTrackerImpl
    extends AdHocDrugTracker
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 787220925605751653L;

// HibernateEntityImpl.vsl merge-point
}