// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see DrugTrackerPlate
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DrugTrackerPlateImpl
    extends DrugTrackerPlate
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 809193187381166980L;

// HibernateEntityImpl.vsl merge-point
}