// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see DrugTrackerTarget
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DrugTrackerTargetImpl
    extends DrugTrackerTarget
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3501511909697140102L;

// HibernateEntityImpl.vsl merge-point
}