// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see DrugTrackerSet
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DrugTrackerSetImpl
    extends DrugTrackerSet
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -606602201535958599L;

// HibernateEntityImpl.vsl merge-point
}