// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see DrugTrackerAlias
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DrugTrackerAliasImpl
    extends DrugTrackerAlias
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2534916310070014539L;

// HibernateEntityImpl.vsl merge-point
}