// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see DrugTracker
 */
// HibernateEntityImpl.vsl annotations merge-point
public abstract class DrugTrackerImpl
    extends DrugTracker
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7851250929468130199L;

// HibernateEntityImpl.vsl merge-point
}