// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package andromda;

/**
 * @see NscDrugTracker
 */
// HibernateEntityImpl.vsl annotations merge-point
public class NscDrugTrackerImpl
    extends NscDrugTracker
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -8786813709166955247L;

// HibernateEntityImpl.vsl merge-point
}